modules/bash: modules/bash/**
modules/docs: modules/docs/**
modules/git: modules/git/**
modules/github: modules/github/**
modules/make: modules/make/**
modules/packages: modules/packages/**
modules/readme: modules/readme/**
modules/semver: modules/semver/**
modules/template: modules/template/**
modules/templateapps: modules/templateapps/**
modules/terraform: modules/terraform/**
